sudo: required
services:
  - docker

before_install:
  - docker build -t doolin/frontend-dockerized -f Dockerfile.dev .

script:
  # - docker run doolin/frontend-dockerized npm run test -- --coverage
  - docker run -e CI=true doolin/frontend-dockerized npm run test -- --coverage
  